02_run_a_command/config/routes.rb
# == Route Map
#
#                                   Prefix Verb   URI Pattern                                                                                       Controller#Action
#                                                 /assets                                                                                           Propshaft::Server
#                                    blogs GET    /blogs(.:format)                                                                                  blogs#index
#                                          POST   /blogs(.:format)                                                                                  blogs#create
#                                 new_blog GET    /blogs/new(.:format)                                                                              blogs#new
#                                edit_blog GET    /blogs/:id/edit(.:format)                                                                         blogs#edit
#                                     blog GET    /blogs/:id(.:format)                                                                              blogs#show
#                                          PATCH  /blogs/:id(.:format)                                                                              blogs#update
#                                          PUT    /blogs/:id(.:format)                                                                              blogs#update
#                                          DELETE /blogs/:id(.:format)                                                                              blogs#destroy
#                          test_root_rails GET    /test_root(.:format)                                                                              rails/welcome#index
#                       rails_health_check GET    /up(.:format)                                                                                     rails/health#show
#                                     demo GET    /demo(.:format)                                                                                   demos#show
#         turbo_recede_historical_location GET    /recede_historical_location(.:format)                                                             turbo/native/navigation#recede
#         turbo_resume_historical_location GET    /resume_historical_location(.:format)                                                             turbo/native/navigation#resume
#        turbo_refresh_historical_location GET    /refresh_historical_location(.:format)                                                            turbo/native/navigation#refresh
#            rails_postmark_inbound_emails POST   /rails/action_mailbox/postmark/inbound_emails(.:format)                                           action_mailbox/ingresses/postmark/inbound_emails#create
#               rails_relay_inbound_emails POST   /rails/action_mailbox/relay/inbound_emails(.:format)                                              action_mailbox/ingresses/relay/inbound_emails#create
#            rails_sendgrid_inbound_emails POST   /rails/action_mailbox/sendgrid/inbound_emails(.:format)                                           action_mailbox/ingresses/sendgrid/inbound_emails#create
#      rails_mandrill_inbound_health_check GET    /rails/action_mailbox/mandrill/inbound_emails(.:format)                                           action_mailbox/ingresses/mandrill/inbound_emails#health_check
#            rails_mandrill_inbound_emails POST   /rails/action_mailbox/mandrill/inbound_emails(.:format)                                           action_mailbox/ingresses/mandrill/inbound_emails#create
#             rails_mailgun_inbound_emails POST   /rails/action_mailbox/mailgun/inbound_emails/mime(.:format)                                       action_mailbox/ingresses/mailgun/inbound_emails#create
#           rails_conductor_inbound_emails GET    /rails/conductor/action_mailbox/inbound_emails(.:format)                                          rails/conductor/action_mailbox/inbound_emails#index
#                                          POST   /rails/conductor/action_mailbox/inbound_emails(.:format)                                          rails/conductor/action_mailbox/inbound_emails#create
#        new_rails_conductor_inbound_email GET    /rails/conductor/action_mailbox/inbound_emails/new(.:format)                                      rails/conductor/action_mailbox/inbound_emails#new
#            rails_conductor_inbound_email GET    /rails/conductor/action_mailbox/inbound_emails/:id(.:format)                                      rails/conductor/action_mailbox/inbound_emails#show
# new_rails_conductor_inbound_email_source GET    /rails/conductor/action_mailbox/inbound_emails/sources/new(.:format)                              rails/conductor/action_mailbox/inbound_emails/sources#new
#    rails_conductor_inbound_email_sources POST   /rails/conductor/action_mailbox/inbound_emails/sources(.:format)                                  rails/conductor/action_mailbox/inbound_emails/sources#create
#    rails_conductor_inbound_email_reroute POST   /rails/conductor/action_mailbox/:inbound_email_id/reroute(.:format)                               rails/conductor/action_mailbox/reroutes#create
# rails_conductor_inbound_email_incinerate POST   /rails/conductor/action_mailbox/:inbound_email_id/incinerate(.:format)                            rails/conductor/action_mailbox/incinerates#create
#                       rails_service_blob GET    /rails/active_storage/blobs/redirect/:signed_id/*filename(.:format)                               active_storage/blobs/redirect#show
#                 rails_service_blob_proxy GET    /rails/active_storage/blobs/proxy/:signed_id/*filename(.:format)                                  active_storage/blobs/proxy#show
#                                          GET    /rails/active_storage/blobs/:signed_id/*filename(.:format)                                        active_storage/blobs/redirect#show
#                rails_blob_representation GET    /rails/active_storage/representations/redirect/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations/redirect#show
#          rails_blob_representation_proxy GET    /rails/active_storage/representations/proxy/:signed_blob_id/:variation_key/*filename(.:format)    active_storage/representations/proxy#show
#                                          GET    /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format)          active_storage/representations/redirect#show
#                       rails_disk_service GET    /rails/active_storage/disk/:encoded_key/*filename(.:format)                                       active_storage/disk#show
#                update_rails_disk_service PUT    /rails/active_storage/disk/:encoded_token(.:format)                                               active_storage/disk#update
#                     rails_direct_uploads POST   /rails/active_storage/direct_uploads(.:format)                                                    active_storage/direct_uploads#create

Rails.application.routes.draw do
  resources :blogs
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  if Rails.env.local?
    # a test only route used by spec/features/it_works_spec.rb
    get "test_root", to: "rails/welcome#index", as: "test_root_rails"
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", :as => :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  resource :demo, only: [:show]

  # Defines the root path route ("/")
  # root "posts#index"
end

02_run_a_command/app/controllers/demos_controller.rb
# frozen_string_literal: true

class DemosController < ApplicationController
  # @route GET /demo (demo)
  def show
  end
end

02_run_a_command/app/views/demos/show.html.erb
<h1>Demos</h1>

<section data-testid="section-rails_link">
  <p>
    a basic <strong>link</strong> via rails <code>link_to</code>
  </p>
  <%= link_to "Demos", demo_path, data: { testid: "rails_link" } %>
</section>

<section data-testid="section-html_input">
  <p>
    a plain <strong>HTML</strong> input tag of <code>type="button"</code>
  </p>
  <input
      type="button"
      onclick="location.href='<%= demo_path %>';"
      value="Demos"
      data-testid="html_input"
  />
</section>

<section data-testid="section-rails_button">
  <p>
    a <strong>rails</strong> <code>button_tag</code>
  </p>

  <%= button_tag(
      "Demos",
      onClick: "location.href='#{demo_path}'",
      data: {
        disable_with: "Please wait...",
        testid: "rails_button",
      },
  ) %>
</section>

<div style="display: flex; flex-direction: row;">
  <section data-testid="section-rails_form">
    <p>
      A <strong>rails</strong> <code>form_for</code> with a submit inside
    </p>

    <%= form_with(url: [:demo], method: :get) do |form| %>
      <%= form.submit(
        value: "Demos",
        data: {
          testid: "rails_form",
        },
      ) %>
    <% end %>
  </section>
  <section data-testid="section-rails_form_loading" style="margin-left: 1em;">
    <p>
      A <strong>rails</strong> <code>form_for</code> with a submit inside with
      <code>enabled/disabled</code> styling
    </p>

    <%= form_with(url: [:demo], method: :get) do |form| %>
      <%= form.button class: 'btn btn-primary', data: { testid: "rails_form_loading" } do %>
        <span class="show-when-enabled">Demos</span>
        <span class="show-when-disabled">fetching ...</span>
      <% end %>
    <% end %>
  </section>
</div>

<section data-testid="section-view_component">
  <p>
    A <strong>view_componewnt</strong> <code>action_button</code> <span
    style="font-style: italic;">using stimulus</span>
  </p>

  <%= render(ActionButtonComponent.new(
      label: "Demos",
      action_url: demo_path,
      icon: "go",
      data: {
        testid: "view_component",
        disable_with: "fetching ...",
      },
  )) %>
</section>

<section data-testid="section-stimulus_component">
  <p>
    A <strong>stimulus</strong> component
  </p>

  <%= button_tag(
      "Demos",
      onClick: "location.href='#{demo_path}'",
      data: {
        disable_with: "fetching ...",
        testid: "stimulus_component",
        controller: "disable",
        action: "click->diable#disableButton",
        disable_target: "button",
      },
  ) %>
</section>